# Generated by Django 5.1.6 on 2025-03-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_product_variant'),
        ('products', '0005_delete_productvariationmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ManyToManyField(related_name='cart_product_variants', to='products.productvariant'),
        ),
    ]
