# Generated by Django 5.1.6 on 2025-03-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_variant'),
        ('products', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ManyToManyField(blank=True, null=True, to='products.productvariant'),
        ),
    ]
