# Generated by Django 5.1.6 on 2025-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderitem_variant_orderitem_variant'),
        ('products', '0008_alter_review_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ManyToManyField(blank=True, to='products.productvariant'),
        ),
    ]
