# Generated by Django 5.1.6 on 2025-02-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
