# Generated by Django 5.1.6 on 2025-02-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount_product_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariationManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
