# Generated by Django 5.1.6 on 2025-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
