# Generated by Django 5.1.6 on 2025-03-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
