# Generated by Django 5.1.6 on 2025-03-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_review_is_reviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
